# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/zabulskyy/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/zabulskyy/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zabulskyy/Projects/Parallel-NN-C++

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zabulskyy/Projects/Parallel-NN-C++

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/zabulskyy/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/zabulskyy/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4445.84/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zabulskyy/Projects/Parallel-NN-C++/CMakeFiles /home/zabulskyy/Projects/Parallel-NN-C++/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zabulskyy/Projects/Parallel-NN-C++/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_test

# Build rule for target.
test_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_test
.PHONY : test_test

# fast build rule for target.
test_test/fast:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/build
.PHONY : test_test/fast

activation.o: activation.cpp.o

.PHONY : activation.o

# target to build an object file
activation.cpp.o:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/activation.cpp.o
.PHONY : activation.cpp.o

activation.i: activation.cpp.i

.PHONY : activation.i

# target to preprocess a source file
activation.cpp.i:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/activation.cpp.i
.PHONY : activation.cpp.i

activation.s: activation.cpp.s

.PHONY : activation.s

# target to generate assembly for a file
activation.cpp.s:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/activation.cpp.s
.PHONY : activation.cpp.s

dense.o: dense.cpp.o

.PHONY : dense.o

# target to build an object file
dense.cpp.o:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/dense.cpp.o
.PHONY : dense.cpp.o

dense.i: dense.cpp.i

.PHONY : dense.i

# target to preprocess a source file
dense.cpp.i:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/dense.cpp.i
.PHONY : dense.cpp.i

dense.s: dense.cpp.s

.PHONY : dense.s

# target to generate assembly for a file
dense.cpp.s:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/dense.cpp.s
.PHONY : dense.cpp.s

neural_network.o: neural_network.cpp.o

.PHONY : neural_network.o

# target to build an object file
neural_network.cpp.o:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/neural_network.cpp.o
.PHONY : neural_network.cpp.o

neural_network.i: neural_network.cpp.i

.PHONY : neural_network.i

# target to preprocess a source file
neural_network.cpp.i:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/neural_network.cpp.i
.PHONY : neural_network.cpp.i

neural_network.s: neural_network.cpp.s

.PHONY : neural_network.s

# target to generate assembly for a file
neural_network.cpp.s:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/neural_network.cpp.s
.PHONY : neural_network.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/test_test.dir/build.make CMakeFiles/test_test.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_test"
	@echo "... activation.o"
	@echo "... activation.i"
	@echo "... activation.s"
	@echo "... dense.o"
	@echo "... dense.i"
	@echo "... dense.s"
	@echo "... neural_network.o"
	@echo "... neural_network.i"
	@echo "... neural_network.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

